<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'phpseclib\\' => array($vendorDir . '/phpseclib/phpseclib/phpseclib'),
    'kornrunner\\' => array($vendorDir . '/kornrunner/keccak/src'),
    'Web3p\\RLP\\' => array($vendorDir . '/web3p/rlp/src'),
    'Web3p\\EthereumUtil\\' => array($vendorDir . '/web3p/ethereum-util/src'),
    'Web3p\\EthereumTx\\' => array($vendorDir . '/web3p/ethereum-tx/src'),
    'Web3\\' => array($vendorDir . '/sc0vu/web3.php/src'),
    'Symfony\\Polyfill\\Php72\\' => array($vendorDir . '/symfony/polyfill-php72'),
    'Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'Symfony\\Polyfill\\Intl\\Normalizer\\' => array($vendorDir . '/symfony/polyfill-intl-normalizer'),
    'Symfony\\Polyfill\\Intl\\Idn\\' => array($vendorDir . '/symfony/polyfill-intl-idn'),
    'Sop\\CryptoTypes\\' => array($vendorDir . '/sop/crypto-types/lib/CryptoTypes'),
    'Sop\\CryptoEncoding\\' => array($vendorDir . '/sop/crypto-encoding/lib/CryptoEncoding'),
    'Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-message/src'),
    'GuzzleHttp\\Psr7\\' => array($vendorDir . '/guzzlehttp/psr7/src'),
    'GuzzleHttp\\Promise\\' => array($vendorDir . '/guzzlehttp/promises/src'),
    'GuzzleHttp\\' => array($vendorDir . '/guzzlehttp/guzzle/src'),
    'Elliptic\\' => array($vendorDir . '/simplito/elliptic-php/lib'),
    'BN\\' => array($vendorDir . '/simplito/bn-php/lib'),
    'BI\\' => array($vendorDir . '/simplito/bigint-wrapper-php/lib'),
    'ASN1\\' => array($vendorDir . '/sop/asn1/lib/ASN1'),
);
